from parsers import FFQParser, fandomParser, WikiquoteParser, GamerescapeParser, TheLifestreamParser, KQ1Parser, KQ5Parser, KQ7Parser, DragonAgeParser, KQCParser, StardewValleyParser, ChronoTriggerParser
from parsers import SuperMarioParser
from parsers import SkyrimParser
from parsers import fandomParser2
from parsers import SimpleMovieScriptParser
from parsers import OblivionParser
from parsers import ElderScrollsWikiParser
from parsers import KQ6Parser
from parsers import FF1Parser
from parsers import DaggerfallParser3
from parsers import FF10Parser,  FF10ParserB, FF10_2Parser
from parsers import MassEffectAParser
from parsers import MassEffect3Parser
from parsers import MassEffect3GibbedParser
from parsers import MassEffect3ExplorerParser
from parsers import MonkeyIslandParser
from parsers import MonkeyIsland2Parser
from parsers import MonkeyIsland3Parser
from parsers import FFVIIParser
from parsers import FF2Parser
from parsers import FF3Parser
from parsers import FF4Parser
from parsers import FF12Parser
from parsers import KQ3Parser
from parsers import KQ4Parser
from parsers import KQ5ParserNES
from parsers import HorizonZeroDawnParser
from parsers import HorizonForbiddenWestParser
from parsers import FF3TranslationParser
from parsers import FFXIII2Parser
from parsers import FFVII_RemakeParser
from parsers import Persona3Parser
from parsers import Persona4Parser
from parsers import Persona5BParser
from parsers import FF8Parser
from parsers import KOTORParser
from parsers import FF9Parser
from parsers import FF9BParser
from parsers import DragonAgeOriginsParser
from parsers import FFXIIILRParser
from parsers import DragonAgeOriginsGameDataParser
from parsers import DragonAge2Parser
from parsers import KingdomHeartsParser
from parsers import TalesOfVesperiaParser
from parsers import KingdomHearts3DParser
from parsers import HadesParser2
from parsers import DiscoElysiumParser
from parsers import jsonCopier
from parsers import YackParser
from parsers import RogueStateParser
from parsers import DragonAgeInqParser